<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class FillCategoriesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $categories = [
            [
                'id' => 1,
                'parent_id' => NULL,
                'name' => 'Arts',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'parent_id' => 1,
                'name' => 'Books',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'parent_id' => 1,
                'name' => 'Design',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'parent_id' => 1,
                'name' => 'Fashion & Beauty',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'parent_id' => 1,
                'name' => 'Food',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'parent_id' => 1,
                'name' => 'Performing Arts',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'parent_id' => 1,
                'name' => 'Visual Arts',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'parent_id' => NULL,
                'name' => 'Business',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'parent_id' => 8,
                'name' => 'Careers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'parent_id' => 8,
                'name' => 'Entrepreneurship',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'parent_id' => 8,
                'name' => 'Investing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'parent_id' => 8,
                'name' => 'Management',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'parent_id' => 8,
                'name' => 'Marketing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'parent_id' => 8,
                'name' => 'Non-Profit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'parent_id' => NULL,
                'name' => 'Comedy',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'parent_id' => 15,
                'name' => 'Comedy Interviews',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'parent_id' => 15,
                'name' => 'Improv',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'parent_id' => 15,
                'name' => 'Stand-Up',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'parent_id' => NULL,
                'name' => 'Education',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'parent_id' => 19,
                'name' => 'Courses',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'parent_id' => 19,
                'name' => 'How To',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'parent_id' => 19,
                'name' => 'Language Learning',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'parent_id' => 19,
                'name' => 'Self-Improvement',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'parent_id' => NULL,
                'name' => 'Fiction',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'parent_id' => 24,
                'name' => 'Comedy Fiction',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'parent_id' => 24,
                'name' => 'Drama',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'parent_id' => 24,
                'name' => 'Science Fiction',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 28,
                'parent_id' => NULL,
                'name' => 'Government',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'parent_id' => NULL,
                'name' => 'History',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 30,
                'parent_id' => NULL,
                'name' => 'Health & Fitness',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 31,
                'parent_id' => 30,
                'name' => 'Alternative Health',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 32,
                'parent_id' => 30,
                'name' => 'Fitness',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 33,
                'parent_id' => 30,
                'name' => 'Medicine',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 34,
                'parent_id' => 30,
                'name' => 'Mental Health',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 35,
                'parent_id' => 30,
                'name' => 'Nutrition',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 36,
                'parent_id' => 30,
                'name' => 'Sexuality',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 37,
                'parent_id' => NULL,
                'name' => 'Kids & Family',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 38,
                'parent_id' => 37,
                'name' => 'Education for Kids',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 39,
                'parent_id' => 37,
                'name' => 'Parenting',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 40,
                'parent_id' => 37,
                'name' => 'Pets & Animals',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 41,
                'parent_id' => 37,
                'name' => 'Stories for Kids',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 42,
                'parent_id' => NULL,
                'name' => 'Leisure',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 43,
                'parent_id' => 42,
                'name' => 'Animation & Manga',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 44,
                'parent_id' => 42,
                'name' => 'Automotive',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 45,
                'parent_id' => 42,
                'name' => 'Aviation',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 46,
                'parent_id' => 42,
                'name' => 'Crafts',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 47,
                'parent_id' => 42,
                'name' => 'Games',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 48,
                'parent_id' => 42,
                'name' => 'Hobbies',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 49,
                'parent_id' => 42,
                'name' => 'Home & Garden',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 50,
                'parent_id' => 42,
                'name' => 'Video Games',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 51,
                'parent_id' => NULL,
                'name' => 'Music',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 52,
                'parent_id' => 51,
                'name' => 'Music Commentary',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 53,
                'parent_id' => 51,
                'name' => 'Music History',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 54,
                'parent_id' => 51,
                'name' => 'Music Interviews',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 55,
                'parent_id' => NULL,
                'name' => 'News',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 56,
                'parent_id' => 55,
                'name' => 'Business News',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 57,
                'parent_id' => 55,
                'name' => 'Daily News',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 58,
                'parent_id' => 55,
                'name' => 'Entertainment News',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 59,
                'parent_id' => 55,
                'name' => 'News Commentary',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 60,
                'parent_id' => 55,
                'name' => 'Politics',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 61,
                'parent_id' => 55,
                'name' => 'Sports News',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 62,
                'parent_id' => 55,
                'name' => 'Tech News',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 63,
                'parent_id' => NULL,
                'name' => 'Religion & Spirituality',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 64,
                'parent_id' => 63,
                'name' => 'Buddhism',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 65,
                'parent_id' => 63,
                'name' => 'Christianity',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 66,
                'parent_id' => 63,
                'name' => 'Hinduism',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 67,
                'parent_id' => 63,
                'name' => 'Islam',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 68,
                'parent_id' => 63,
                'name' => 'Judaism',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 69,
                'parent_id' => 63,
                'name' => 'Religion',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 70,
                'parent_id' => 63,
                'name' => 'Spirituality',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 71,
                'parent_id' => NULL,
                'name' => 'Science',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 72,
                'parent_id' => 71,
                'name' => 'Astronomy',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 73,
                'parent_id' => 71,
                'name' => 'Chemistry',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 74,
                'parent_id' => 71,
                'name' => 'Earth Sciences',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 75,
                'parent_id' => 71,
                'name' => 'Life Sciences',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 76,
                'parent_id' => 71,
                'name' => 'Mathematics',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 77,
                'parent_id' => 71,
                'name' => 'Natural Sciences',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 78,
                'parent_id' => 71,
                'name' => 'Nature',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 79,
                'parent_id' => 71,
                'name' => 'Physics',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 80,
                'parent_id' => 71,
                'name' => 'Social Sciences',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 81,
                'parent_id' => NULL,
                'name' => 'Society & Culture',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 82,
                'parent_id' => 81,
                'name' => 'Documentary',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 83,
                'parent_id' => 81,
                'name' => 'Personal Journals',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 84,
                'parent_id' => 81,
                'name' => 'Philosophy',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 85,
                'parent_id' => 81,
                'name' => 'Places & Travel',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 86,
                'parent_id' => 81,
                'name' => 'Relationships',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 87,
                'parent_id' => NULL,
                'name' => 'Sports',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 88,
                'parent_id' => 87,
                'name' => 'Baseball',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 89,
                'parent_id' => 87,
                'name' => 'Basketball',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 90,
                'parent_id' => 87,
                'name' => 'Cricket',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 91,
                'parent_id' => 87,
                'name' => 'Fantasy Sports',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 92,
                'parent_id' => 87,
                'name' => 'Football',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 93,
                'parent_id' => 87,
                'name' => 'Golf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 94,
                'parent_id' => 87,
                'name' => 'Hockey',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 95,
                'parent_id' => 87,
                'name' => 'Rugby',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 96,
                'parent_id' => 87,
                'name' => 'Running',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 97,
                'parent_id' => 87,
                'name' => 'Soccer',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 98,
                'parent_id' => 87,
                'name' => 'Swimming',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 99,
                'parent_id' => 87,
                'name' => 'Tennis',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 100,
                'parent_id' => 87,
                'name' => 'Volleyball',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 101,
                'parent_id' => 87,
                'name' => 'Wilderness',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 102,
                'parent_id' => 87,
                'name' => 'Wrestling',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 103,
                'parent_id' => NULL,
                'name' => 'Technology',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 104,
                'parent_id' => NULL,
                'name' => 'True Crime',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 105,
                'parent_id' => NULL,
                'name' => 'TV & Film',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 106,
                'parent_id' => 105,
                'name' => 'After Shows',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 107,
                'parent_id' => 105,
                'name' => 'Film History',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 108,
                'parent_id' => 105,
                'name' => 'Film Interviews',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 109,
                'parent_id' => 105,
                'name' => 'Film Reviews',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 110,
                'parent_id' => 105,
                'name' => 'TV Reviews',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('categories')->insert($categories);
    }
}
